<? $gam3 = GetAge("2013-01-07"); ?>

<p>My name is Spencer "Vael" Victus. I'm a web developer, game designer, and writer from South Carolina, USA. I work for a global financial investment company and make web games in my spare time. I'm father to a <a href='<?=$this->webroot?>img/abel.jpg' target='_blank' class='aj-stop'>boy named Abel</a> and I'm married to the incomparable <a href='http://evevictus.deviantart.com' target='_blank'>Evelyn Victus</a>. I publish my games under a microstudio named <a href='https://tinydark.com'>tinydark</a>.</p>

<p>The games and websites I make are <a href='https://medium.com/@amberleyjohanna/seriously-though-what-is-a-progressive-web-app-56130600a093' target='_blank'>Progressive Web Apps</a>. That means they can be saved to a user's phone the same way a native app would be, which allows my products to be much more than simply websites or "browser-based" games. Web technology is rapidly maturing to the point that our websites also function as native applications, and soon, there will be no codebase-splitting required to make that true. I aim to recreate the traditional desktop/mobile gaming experience through the browser. This means I use 100% of available screen space, employ sound and music, a single <span style='font-size: 0.9em'>PLAY</span> button to begin the game, and generally try for the feel of a game. (settings menu, <span style='font-size: 0.9em'>QUIT</span>)</p>

<p>I'm deeply interested in the topic of ethical gaming, and as such, tinydark is founded on ethics. It is the studio's goal to put the player first, and provide them with memorable experiences realized through the marriage of narrative and game design. Our designs respect the player's time while keeping them engaged. Premium currency purchasing is straightforward and makes it clear what's being spent.</p>

<p>I am an industrious and avid life-long learner, and I spend much of my recreation time working on my hobby projects or reading. I'm a huge fan of <a href='https://jamesclear.com/' target='_blank'>James Clear</a>'s psychology, especially his articles about <a href='https://jamesclear.com/productivity' target='_blank'>productivity</a>. I follow <a href='https://jamesclear.com/habit-triggers' target='_blank'>trigger-based habits</a> and prefer to keep my work separate from my play.</p>

<p>Visit <a href='https://tinydark.com/about' target='_blank'>tinydark's website</a> for a rolling history of what I'm up to.</p>